---
title: "USRDS2015: Refactoring of USRDS"
subtitle: "Project Notebook"
author: Abhijit Dasgupta
date: "Last updated `r format(Sys.Date(), '%B %d, %Y')`"
output: html_notebook
---

# Background

I will be re-factoring the original USRDS project to make it simpler and more efficient to use in 
R. The main improvements planned are:

1. Incorporating data into SQLite and MonetDB databases for easier data munging
2. Improving computation by incorporating more recent developments in competing risks modeling


# Software

I'm putting all the datasets in on-disk SQL-based storage, using 
SQLite and MonetDB. The latter is a bit more finicky to set up but 
is quite a bit quicker for the datasets. MonetDB is installed and used 
through the `MonetDBLite` R package. SQLite is installed and used through the `RSQLite` R package. 

There may be value to doing data manipulation in Spark, even on a local Spark instance, given the sizes of the data sets. The rate-limiting 
factor may be copying the data sets into Spark. However, the munging and descriptives might be much faster. 

The current plan (6/29/17) is to do select and join functions in the SQL
databases, import those into R, and then do mutate and distinct operations. These can possibly be exported into Spark with much lower 
overhead on memory operationally.

# Updates

### June 27, 2017
I created a function (`verifyPaths`) that automatically captures the database directory from 
the external disk label. The databases are on one of two external HDs. Backups of the raw data are on the P: drive. 

### October 18, 2017
I added to `verifyPaths` to include my laptop. 

__REREDISFOL analysis__

We first extract data from `AnalyticData`, which was our study dataset for the 2014 
analysis, using `censtype==3`. We then used a left join to append the REREDISFOL data 
to it and looked at frequency counts of what was available within the discontinued group.

```
# A tibble: 7 x 3
                  REREDISFOL     n         perc
                       <chr> <int>        <dbl>
1                               10  0.006193369
2       HD/PD access failure  1075  0.665787208
3          Failure to thrive 52180 32.317001418
4 Acute medical complication 33275 20.608436608
5                      Other 65677 40.676192069
6                    Unknown  8890  5.505905378
7                    Missing   356  0.220483950
```

__Hospitalization analysis__

We're looking at incident comorbidities from the 2015 hospitalization data. For this
we're extracting IDs for people with these comorbidities in the hospital files. Then
we will verify that these are incident cases by removing individuals who also had the 
same ICD9 codes in their medevid file. 

We also decided to extend the analysis to 2015 for completeness, working with the 
1,131,409 individuals we did for the 2014 analysis and not adding new individuals.
The data for the first analysis is in the `AnalyticData` table in the 2014 SQLite 
database.

# November 29, 2017

1. Updated dB to have dates as text

__Hospitalization data__  

One of the issues in the 2015 data is that there are entries that are earlier than the entry time of 2003-01-01
for many of the patients. This can result in incompatible results. I'm deferring the normalization of the 
2014 and 2015 data, so that I can create the infrastructure to actually do the analysis for discontinuation we
need, knowing that some of the dates of death, discontinuation, and entry do not tally with the 2014 data 
(see `UpdateTo2015.R` for some of the details). 

We should use CLM_FROM as the date of event

-----

## File updates
- [October 27, 2017] Copied PR_db at work to P:/Work/Ward/Studies/USRDS/2014 Data
- [October 27, 2017] Added the 2014 study ids to the 2015 database (in `StudyIDs`)
- [October 27, 2017] Note that dates in 2015 DB have base as 1970-01-01 (R style), while those in 2014 have base as 1960-01-01 (SAS style)
- [November 22, 2017] Updated `Ingest_to_DB.R` to convert dates to text. Ran on home disk
- [November 29, 2017] Ran `Ingest_to_DB.R` on P drive to convert dates to text in DB.
- [November 29, 2017] Wrote `graph_discontinue.R`

